In [ ]:
Skript für Kapitel 4 und Übungsblatt 9 wurde geupdatet

In [ ]:
Suchen III 

In [ ]:
Underlying Theme Today: Suche in O(1)
    
    Durch Strukturierung in Bäumen haben wir Suche im Vgl zu linearer Suche schon von O(n) auf O(ln(n)) verbessert!
            (Einfügen, Löschen, Suchen in O(ln(n)))
    
    Können wir noch schneller werden?
    Bitvektoren: Suche in O(1) allerdings Problem, dass Initialisierung uns O(n) kostet!
        
    Hashing =Streuspeicherung: Yay, Suche in O(1) möglich - wenn da nicht KOLLISIONEN wären =/

In [ ]:
#Geburtstagsparadox

In [22]:
def geburtstagsparadox(n):
    pct=1
    for i in range(n):
        pct=pct*(365-i)/365
        print(pct)

In [32]:
geburtstagsparadox(30)

1.0
0.9972602739726028
0.9917958341152185
0.9836440875334497
0.9728644263002063
0.9595375163508884
0.9437642969040244
0.9256647076483308
0.905376166110833
0.8830518222889221
0.8588586216782667
0.8329752111619353
0.8055897247675702
0.7768974879950266
0.7470986802363133
0.7163959947471498
0.6849923347034391
0.6530885821282105
0.6208814739684632
0.5885616164194198
0.5563116648347941
0.5243046923374498
0.49270276567601445
0.4616557420854711
0.431300296030536
0.40175917986406096
0.37314071773675794
0.3455385276576005
0.319031462522223
0.2936837572807313


In [ ]:
9.1. Bitvektoren

In [ ]:
Gegeben ist wieder die Sammlung von Informatik-Fachbüchern: 
    
Nummer Titel Autor Jahr Kurzel 
0 Design Patterns E. Gamma, et al. 1994 DP
1 Clean Code Robert C. Martin 2008 CC
2 Make Your Own Neural Network Tariq Rashid 2016 MNN
3 Agile Software Development Robert C. Martin 2002 AgSD
4 Introduction to Algorithms T. H. Cormen, et al. 1989 IA
5 Functional Thinking: Paradigm Over Syntax Neal Ford 2014 FuT
6 Extreme Programming Explained: Embrace Change Kent Beck 1999 ExPE
7 Algorithms for Reinforcement Learning Csaba Szepesvari 2010 AlRL
8 The Software Craftsman Robert C. Martin 2014 TheSC
9 Test Driven Development: By Example Kent Beck 2002 TDD
10 Programming Pearls Jon Bentley 1986 PP
11 Building Your Own Compiler with C++ Jim Holmes 1994 BYOC


Das Universum U soll im folgendem alle obigen Bucher enthalten. Ein Eintrag, Bit[i] eines Bitvektors steht
dafür, ob ein Buch mit Nummer i in einer gegebenen Menge enthalten ist.
Hinweis: Sie dürfen die Vektoren als Zeilenvektoren schreiben. 

In [ ]:
9.1.a) Geben Sie die Größe des Universums N=|U| an





--> N=12

In [ ]:
9.1.b) Geben Sie den Bitvektor an, der das Universum repräsentiert.




--> Bit(U) = (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)



Wie viele Elemente (Bücher) enthält die Menge, die er repräsentiert.



--> Die Menge enthalt natürlich genau N = 12 Elemente(Bücher).

In [ ]:
9.1.c) Welcher Bitvektor repräsentiert folgende Menge an Büchern  M = {ASD, TDD, BYOC, IA, TSC}?


In [29]:
a=['DP','CC','MYONN','ASD','IA','FT','EPE','ARL','TSC','TDD','PP','BYOC']
b=['ASD','TDD','BYOC','IA','TSC']
c=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
for b in b:
    if b in a:
        index=a.index(b)
        c[index]=1

In [30]:
c

[0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1]

In [ ]:
9.1.d) Welche Menge reprasentiert der Bitvektor M = [1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0]

In [34]:
a=['DP','CC','MYONN','ASD','IA','FT','EPE','ARL','TSC','TDD','PP','BYOC']
M = [1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
d=[]
for i in range(len(M)):
    if M[i]==1:
        d.append(a[i])
        

In [35]:
d

['DP', 'ASD', 'IA', 'FT', 'TDD']

In [ ]:
9.1.e) Wie könnte ein effizienter Algorithmus aussehen, der mittels zweier Bitvektoren Bit(M1) und Bit(M2)
die Schnittmenge der Mengen, die sie repräsentieren ( M1 und M2), berechnet und diese
wieder als Bitvektor Bit(Mresult) ausgibt? Geben Sie diesen Algorithmus an

In [40]:
#Bitvektor aus d)
M1 = [1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
#anderer Bitvektor
M2 = [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0]
M3=[]
for i in range(12):
    M3.append(0)
    
for i in range(len(M1)):
    if M1[i]==M2[i]:
        M3[i]=M1[i]


        

In [41]:
M3

[1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0]

In [ ]:
PseudoCode:
Algorithmus schnitt(Bit(M_1), Bit(M_2)):
    Bit(M_result) = Initialize new Bitvektor
    for i = 0 bis N-1
        Bit(M_result)[i] = Bit(M_1)[i] AND Bit(M_2)[i]
    return Bit(M_result)


In [ ]:
jetzt das gleiche für Vereinigungsmenge:

In [42]:
#Bitvektor aus d)
M1 = [1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0]
#anderer Bitvektor
M2 = [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0]
M3=[]
for i in range(12):
    M3.append(0)
    
for i in range(len(M1)):
    if M1[i]==1:
        M3[i]=M1[i]
    if M2[i]==1:
        M3[i]=M2[i]        

In [43]:
M3

[1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0]

In [ ]:
Algorithmus vereinigung(Bit(M_1), Bit(M_2)):
    Bit(M_result) = Initialize new Bitvektor
    for i = 0 bis N-1
        Bit(M_result)[i] = Bit(M_1)[i] OR Bit(M_2)[i]
    return Bit(M_result)

In [ ]:
Laufzeit?






Die Laufzeit ermittelt sich folgendermaßen:
• Die Initialisierung benötigt O(N) (siehe Vorlesung)
• Die for-Schleife wird N mal durchlaufen ⇒ O(N)
• Innerhalb der for-Schleife finden zwei Suchen nach Elementen statt, diese sind in konstanter Zeit
durchführbar (siehe Vorlesung), die logischen Operationen ( ∧ und ∨) bzw. (’AND’ und ’OR’)
sind ebenfalls in konstanter Zeit durchführbar. 

Eine Iteration ist also in O(1) durchfuhrbar. 

Insgesamt ergibt sich fur die Laufzeit also: ¨ O(N + N ∗ 1) = O(N)

In [ ]:
9.2. Hashing Offenes Hashing mit geschlossener Adressierung

In [ ]:
perfekt




wenn keine Kollisionen

In [ ]:
minimal



wenn hash-datenbank genau so viele einträge, wie die Datenbank

In [ ]:
Gegeben sei folgende Hashfunktion h(k) = kmod 7 

Fügen sie nun nacheinander folgende Schlüssel in eine Hashtabelle ein.

Verwenden Sie dabei Offenes Hashing mit geschlossener Adressierung:

In [ ]:
9.2.a) a=[1, 7, 13, 15, 14, 5]

In [1]:
import numpy as np
a=np.array([1, 7, 13, 15, 14, 5])
b=a%7
b

array([1, 0, 6, 1, 0, 5])

In [ ]:
als tabelle mit offenem hashing mit geschlossener adressierung:
    0->7->14
    1->1->15
    2
    3
    4
    5->5
    6->13

In [ ]:
9.2.b) c, z, a, j, v, k, l 
        (überlegen wie man Buchstaben in Hashfunktion einfügen kann)

In [ ]:
zB ORD-Funktion: ORD(a)=1, ORD(b)=2, ...Ord(z)=26
    0
    1->a->v
    2
    3->c->j
    4->k
    5->z->l
    6

In [ ]:
9.3. Geschlossenes Hashing mit offener Adressierung

In [ ]:
Gegeben sind die Zahlen {13, 7, 31, 19, 27, 42, 69, 96} welche in eine Hashtabelle der Große 11 eingeordnet 
werden sollen

In [ ]:
9.3.a) Benutzen Sie geschlossenes Hashing mit h(k) = k mod 11 
und ordnen Sie die Zahlen ein. 
Kennzeichnen Sie Kollisionen und 
lösen Sie diese durch polynomielles (genauer lineares) sondieren. 

In [3]:
a=np.array([13, 7, 31, 19, 27, 42, 69, 96])
b=a%11






print(a)
print(b)

[13  7 31 19 27 42 69 96]
[2 7 9 8 5 9 3 8]


In [ ]:
geschlossenes Hashing mit linearem Sondieren:
13 → 2
7 → 7
31 → 9
19 → 8
27 → 5
42 → 9 → 10
69 → 3
96 → 8 → 9 → 10 → 0

In [ ]:
9.3.b) Nutzen Sie nun Doppel-Hashing mit h0(k) = k mod 11, 
der Sekundaren Hashfunktion h1(k)= k mod 9 + 1
und der Sondierungsfunktion h_j(k) = (h0(k)+j*h1(k))mod 11 mit j=1,2,3,...

In [4]:
print(a)
print(b)

[13  7 31 19 27 42 69 96]
[2 7 9 8 5 9 3 8]


In [ ]:
doppeltes Hashing:
13 → 2
7 → 7
31 → 9
19 → 8
27 → 5
42 → 9 : h_{j=1}(42) = (h0(42) + 1 * h1(42))mod11=5 →  h_{j=2}(42) = (h0(42) + 2 * h1(42)) mod11 = 1
69 → 3
96 → 8 → h_{j=1}=11(96) = (h0(96) + 1 ∗ h1(96))mod11 = 4

In [15]:
((42%11)+1*((42%9)+1))%11

5

In [14]:
((42%11)+2*((42%9)+1))%11

1

In [17]:
((96%11)+1*((96%9)+1))%11

4